# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='flask-app',
    version='1.1.0',
    python_requires='==3.*,>=3.7.0',
    author='Eduard Kracmar',
    author_email='eduard.kracmar@hotovo.org',
    packages=['flask_app'],
    package_data={},
    install_requires=[
        'click==7.0', 'flask==1.1.1', 'gunicorn==20.0.0', 'itsdangerous==1.1.0',
        'jinja2==2.10.3', 'markupsafe==1.1.1', 'werkzeug==0.16.0'
    ],
)
